### PR TITLE
fix: return-null-value

### LINKED ISSUE #202: Call to a member function getProductIds() on null
Issue Brief
--
What is the purpose of this issue? Explain the background context.

Resolve the error:
Call to a member function getProductIds() on null

Which i sometimes see in the error logs.

Environment
--
* PHP Version: (8.1)
* Magento Version: 2.4.6-p6
* Tweakwise Version: 6.0.1
* Tweakwise Export Version: 7.0.1
* Magento Deploy Mode: production
* Third party modules:
Trace does not have any third party modules visible.

Steps to reproduce
--
1. \Tweakwise\Magento2Tweakwise\Model\Catalog\Layer\NavigationContext:getResponse returns null which is possible when looking at the function return type.
2. \Tweakwise\Magento2Tweakwise\Model\Catalog\Product\Collection::getProductIds 
`        
$response = $this->navigationContext->getResponse();
        return $response->getProductIds();
`
3. this returns an empty array.

Actual result
--
1. $response is null and than it cannot call getProductIds() on null.
2. you get the following error:
3. Error: Caught Error (500): Call to a member function getProductIds() on null

Expected result
--
1. if $response is null than $response->getProductIds() will not be called.

Possible solution
```
diff --git a/vendor/tweakwise/magento2-tweakwise/Model/Catalog/Product/Collection.php b/vendor/tweakwise/magento2-tweakwise/Model/Catalog/Product/Collection.php
--- a/vendor/tweakwise/magento2-tweakwise/Model/Catalog/Product/Collection.php
+++ b/vendor/tweakwise/magento2-tweakwise/Model/Catalog/Product/Collection.php	(date 1719832609005)
@@ -148,6 +148,6 @@
     protected function getProductIds()
     {
         $response = $this->navigationContext->getResponse();
-        return $response->getProductIds();
+        return $response->getProductIds() ?? [];
     }
 }
```

### PR DESCRIPTION
**Pull request by ahuininga-orisha**
This fixes #202 

Instead of checking everywhere if the value is null. The value should never be null. The value could only be null if an previous call to tweakwise failed.

I've changed two things to prevent null from being returned.

- Changed that an 404 request is seen as an tweakwise exception. This occurs when you're requesting recommendations for an product that is no longer available in TW.
- Changed that if there previous was an connection issue. An api exception is thrown. This causes magento to fallback to default functionality instead of an empty result.

### CODE REVIEW

File: Model/Client.php [hunk 1]
```diff
@@ -331,9 +331,9 @@ public function request(Request $request, bool $async = false)
         try {
             return $this->doRequest($request, $async);
         } catch (ApiException $e) {
-            $this->config->setTweakwiseExceptionThrown(true);
             //don't log 404 messages.
             if ($e->getCode() !== 404) {
+                $this->config->setTweakwiseExceptionThrown(true);
```
Comment (jansentjeu) [inline Model/Client.php:336]: Why is this moved?

**Review by jansentjeu — CHANGES_REQUESTED** [review]

File: Model/Client.php (hunk 1 above)
Comment (ahuininga-orisha) [reply Model/Client.php:336]: Because tweakwise returning an 404 (for example recommendations if the product no longer exists in TW) is not an connection exception. 

The setTweakwiseExeptionTrown function is used to determine if the next call to TW (in the current request) needs to be executed. And only if there are connection issues you need to skip it and use default magento functionalty.
The function prevents pages which have several different TW calls to wait for an timeout on each TW request if there are connection issues.

**Review by jansentjeu — APPROVED** [review]
